import { useEffect, useState } from "react";

export type BusinessStatus = "pending" | "verified" | "assigned" | "scheduled" | "picked_up" | "delivered" | "completed" | "cancelled";
export interface BusinessDonation { id: string; food: string; category: string; quantity: number; unit: string; servings: number; pickup: string; pickupDate: string; window: string; employee: string; status: BusinessStatus; createdAt: string; notes: string; }
const seed: BusinessDonation[] = [
  { id: "DON-1048", food: "Prepared meals", category: "Prepared Meals", quantity: 25, unit: "kg", servings: 100, pickup: "123 Main Street, Downtown", pickupDate: "2026-09-06", window: "6:00 PM - 7:00 PM", employee: "Alex Morgan", status: "assigned", createdAt: "2026-09-06T10:00:00Z", notes: "Sealed and refrigerated. Use loading dock B." },
  { id: "DON-1024", food: "Bakery assortment", category: "Bakery", quantity: 18, unit: "kg", servings: 72, pickup: "123 Main Street, Downtown", pickupDate: "2026-09-04", window: "5:00 PM - 6:00 PM", employee: "Jamie Lee", status: "completed", createdAt: "2026-09-04T09:00:00Z", notes: "Keep bags upright." },
];
const donationKey = "foodflow_business_donations";
export function useBusinessDonations() { const [donations, setDonations] = useState<BusinessDonation[]>(() => { try { return JSON.parse(localStorage.getItem(donationKey) || "null") || seed; } catch { return seed; } }); useEffect(() => localStorage.setItem(donationKey, JSON.stringify(donations)), [donations]); const add = (input: Omit<BusinessDonation, "id" | "createdAt" | "status" | "employee">) => { const donation = { ...input, id: `DON-${Math.floor(1000 + Math.random() * 8999)}`, createdAt: new Date().toISOString(), status: "pending" as BusinessStatus, employee: "Awaiting assignment" }; setDonations((current) => [donation, ...current]); return donation; }; const update = (id: string, patch: Partial<BusinessDonation>) => setDonations((current) => current.map((item) => item.id === id ? { ...item, ...patch } : item)); return { donations, add, update }; }
export function useBusinessPreferences() { const [values, setValues] = useState<Record<string, boolean>>(() => { try { return JSON.parse(localStorage.getItem("foodflow_business_preferences") || "{}"); } catch { return {}; } }); useEffect(() => localStorage.setItem("foodflow_business_preferences", JSON.stringify(values)), [values]); return { values, setValue: (key: string, value: boolean) => setValues((current) => ({ ...current, [key]: value })) }; }
